#!/usr/bin/env bash
#install nginx and update my headername 
sudo apt update
sudo apt install -y nginx
sudo sed -i '/http {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx restart
echo "Nginx configured with custom header X-Served-By."
