#!/usr/bin/env bash
#configure roundrobin loadbalancer
sudo apt update
sudo apt -y install haproxy
echo -e "frontend httpd\n\tbind *:80\n\tdefault_backend web-backend" | sudo tee -a /etc/haproxy/haproxy.cfg >/dev/null
echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver web01 34.224.5.51:80 check\n\tserver web02 54.162.89.99:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg >/dev/null
sudo service haproxy start