#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop

# Initializing counter

i=1

while [ $i -lt 21 ]
do
    case $i in
	9)
	    echo $i
	    echo "bad luck from Japan"
	    ;;
	4)
	    echo $i
	    echo "bad luck from China"
	    ;;
	17)
	    echo $i
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo $i
	    ;;
    esac
	((i++))
done
